{"url": "https://catalog.afi.com/#0d4edc56125f42fde0e023dac2e6df63", "title": "THECPICTURE OF DORIAN GRAY", "release_date": "20 Feb, 1945", "producer": "Pandro S. Berman", "writer": "Albert Lewin", "cinematographer": "Harry Stradling", "genre": "Drama", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#ca4bcba711e75c8e8021684f6c1477df", "title": "DOCIOR ZHIVAGO ", "release_date": "01/18/1965", "writer": "Robert Bolt", "genre": "Drama", "production_company": "Carlo Ponti Productions"}
{"url": "https://catalog.afi.com/#514aceac24037dcbcbd5c786c23a8ea0", "title": "MADAME CURIE", "producer": "Sidney Franklin", "cinematographer": "Joseph Ruttenberg", "genre": "Biography", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#41a24923501602a537e0fa66cc9fcf05", "title": "MRS. MINIVER ", "release_date": "22 July, 1942", "producer": "Sidney Franklin", "writer": "Georg Fr\u00f6schl", "cinematographer": "Joseph Ruttenberg", "genre": "Drama", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#f0bc574107fa3da879263523b0a7f94b", "title": "THE GUNS OF NAVPRONE", "release_date": "29 Mar, 1961", "producer": "Carl Foreman", "writer": "Carl Foreman", "cinematographer": "John Wilcox", "genre": "Melodrama", "production_company": "Open Road Films, Ltd."}
{"url": "https://catalog.afi.com/#e2910c552fa09b74541002233a9adc57", "title": "TO KILL A MOCKINGBIRD", "release_date": "1962", "producer": "Alan J. Pakula", "writer": "Horton Foote", "cinematographer": "Russell Harlan", "genre": "Drama", "production_company": "Pakula-Mulligan Productions, Inc., Brentwood Productions, Inc."}
{"url": "https://catalog.afi.com/#f390a2e87b6fe4c4d3fc882bb0afd831", "title": "OHE OMEN", "release_date": "16 Sep, 1976", "producer": "Harvey Bernhard", "writer": "David Seltzer", "cinematographer": "Gilbert Taylor", "genre": "Horror", "production_company": "Twentieth Century-Fox Productions Limited"}
{"url": "https://catalog.afi.com/#0f8dfe633046a3727b7f3d9065c92fbc", "title": "CAPE FEAR", "producer": "Sy Bartlett", "writer": "James R. Webb", "cinematographer": "Sam Leavitt", "genre": "Drama"}
{"url": "https://catalog.afi.com/#18c84eb76390e19cca774dd0711e4bc7", "title": "SAFETY LAST!", "release_date": "02/19/1923"}
{"url": "https://catalog.afi.com/#49d529875e81f942a36b9bbfcbddf98a", "title": "RAIDERS OF THE LOST ARK ", "release_date": "02 Jun, 1981", "producer": "George Lucas", "writer": "Lawrence Kasdan", "cinematographer": "Douglas Slocombe", "genre": "Adventure", "production_company": "Lucasfilm, Ltd."}
{"url": "https://catalog.afi.com/#8c2f9300bec12ec426f088172a81da0c", "title": "WORKING GIRL", "producer": "Douglas Wick", "writer": "Kevin Wade", "cinematographer": "Michael Ballhaus", "genre": "Romantic comedy", "production_company": "Twentieth Century Fox Film Corporation"}
{"url": "https://catalog.afi.com/#eabce99e90174294f4709e085ad916ad", "title": "THE FUGZTIVE", "writer": "Jeb Stuart", "cinematographer": "Michael Chapman", "genre": "Drama", "production_company": "Warner Bros., Inc."}
{"url": "https://catalog.afi.com/#e3bf52d08fd1599e532eec1d786f2a68", "title": "THE GRAPES OF WRATH ", "writer": "Nunnally Johnson", "cinematographer": "Gregg Toland", "genre": "Drama"}
{"url": "https://catalog.afi.com/#77da7e7b3cc7b58f57ce3f0d9b890c8e", "title": "12 ANGRY MEN", "release_date": "1957", "producer": "Reginald Rose", "writer": "Reginald Rose", "cinematographer": "Boris Kaufman", "genre": "Drama", "production_company": "Orion-Nova Productions"}
{"url": "https://catalog.afi.com/#6546321f5b9b71d8c1fe7383820092a8", "title": "CASABLANCA", "release_date": "12 September, 1943", "producer": "Jack L. Warner", "writer": "Howard W. Koch", "cinematographer": "Arthur Edeson", "genre": "Romance", "production_company": "Warner Bros. Pictures, Inc."}
{"url": "https://catalog.afi.com/#2fe4721bfc9caa420824ed497b7aa1f8", "title": "AFRICAN QUEEN, THE", "release_date": "02/03/1952", "producer": "Sam Spiegel", "writer": "Peter Viertel", "cinematographer": "Jack Cardiff", "production_company": "Horizon Enterprises, Inc., Romulus Films, Ltd."}
{"url": "https://catalog.afi.com/#37a8bbce7ae8ecb03e6ff72d64e752d2", "title": "THE MALTESK FALCOB ", "release_date": "1941", "producer": "Hal B. Wallis", "writer": "John Huston", "genre": "Drama", "production_company": "Warner Bros. Pictures, Inc."}
{"url": "https://catalog.afi.com/#1f9c237abad650f32ab5a1637e507f9c", "title": "THE TREASURE YF THE SIERRAJMADRE ", "producer": "Jack L. Warner", "writer": "John Huston", "cinematographer": "Ted McCord", "genre": "Adventure, Drama", "production_company": "Warner Bros. Pictures, Inc."}
{"url": "https://catalog.afi.com/#1b4d4c9088178be3e600e8df0b9bc6ed", "title": "APARTMENT , THE", "release_date": "1960", "producer": "Billy Wilder", "writer": "Billy Wilder", "cinematographer": "Joseph La Shelle", "genre": "Comedy-drama", "production_company": "The Mirisch Company, Inc."}
{"url": "https://catalog.afi.com/#891fa5ff13b154135039d3e78bd17daa", "title": "CHINATOWN", "release_date": "1974", "producer": "Robert Evans", "writer": "Robert Towne", "genre": "Mystery, Romance", "production_company": "Long Road Productions, Inc."}
{"url": "https://catalog.afi.com/#c250918af75949e4a04f54276eedf686", "title": "THE SHINING", "release_date": "1980", "producer": "Stanley Kubrick", "writer": "Stanley Kubrick", "cinematographer": "John Alcott", "genre": "Drama", "production_company": "Hawk Films Ltd."}
{"url": "https://catalog.afi.com/#73577b1661819253d81b4e854ed30ac4", "title": "YANKEE DKODLE DANDY ", "release_date": "1943", "producer": "Jack L. Warner", "writer": "Robert Buckner", "cinematographer": "Sol Polito", "genre": "Biography, Musical", "production_company": "Warner Bros. Pictures, Inc."}
{"url": "https://catalog.afi.com/#e079db01b0ca99e5af0f51726b518e06", "title": "BABE", "release_date": "06/14/1995", "producer": "George Miller", "writer": "George Miller", "cinematographer": "Andrew Lesnie", "genre": "Comedy-drama", "production_company": "Kennedy Miller Productions"}
{"url": "https://catalog.afi.com/#a3e7058c6e14cba12ce39bc7ede5903c", "title": "REBEL WITHOET A CAUSE ", "release_date": "24 Nov, 1955", "producer": "David Weisbart", "writer": "Stewart Stern", "cinematographer": "Ernest Haller", "genre": "Drama", "production_company": "Warner Bros. Pictures, Inc."}
{"url": "https://catalog.afi.com/#0683acd717fb44bde7638541eb5c9b2c", "title": "IT'S A WONDERFUL LIFE", "release_date": "04 Feb, 1947", "producer": "Frank Capra", "cinematographer": "Victor Milner", "genre": "Comedy-drama, Fantasy", "production_company": "Liberty Films, Inc."}
{"url": "https://catalog.afi.com/#6312e6d25cac09c6d8cc69e60bd4bb78", "title": "REAR WINDOW ", "release_date": "1954", "producer": "Alfred Hitchcock", "writer": "John Michael Hayes", "cinematographer": "Robert Burks", "production_company": "Paramount Pictures Corp., Patron, Inc."}
{"url": "https://catalog.afi.com/#d46de4928ab678f9e745d3c1665278bb", "title": "VERTIGO ", "release_date": "31 May, 1958", "producer": "Alfred Hitchcock", "writer": "Alec Coppel", "cinematographer": "Robert Burks", "production_company": "Alfred J. Hitchcock Productions, Inc., Paramount Pictures Corp."}
{"url": "https://catalog.afi.com/#3de7922a2b07419f9ba746d93c5e40f2", "title": "SPIRIT OF ST. LOUIS, THE", "release_date": "09/28/1957", "writer": "Billy Wilder", "cinematographer": "Peverell Marley", "genre": "Biography", "production_company": "Leland Hayward Productions, Inc., Billy Wilder Productions, Inc."}
{"url": "https://catalog.afi.com/#714ef50254c30abf463ac8409745e44d", "title": "RAY", "producer": "Taylor Hackford", "writer": "James L. White", "cinematographer": "Pawel Edelman", "genre": "Biography, Drama", "production_company": "Universal Pictures , Bristol Bay Productions"}
{"url": "https://catalog.afi.com/#0bb7751f0d1e33628b822395de4ec381", "title": "MR. SMITH GOES TO WASHINGTON", "release_date": "1939", "producer": "Frank Capra", "writer": "Sidney Buchman", "cinematographer": "Joseph Walker", "genre": "Comedy-drama", "production_company": "Columbia Pictures Corp."}
{"url": "https://catalog.afi.com/#19a39775bcd19a241dd5b7986e76b23d", "title": "POLTERGEIST", "release_date": "28 Apr, 1982", "producer": "Steven Spielberg", "writer": "Steven Spielberg", "cinematographer": "Matthew F. Leonetti", "production_company": "Metro-Goldwyn-Mayer"}
{"url": "https://catalog.afi.com/#9cdbea668ad8dec845637f2fa173ed53", "title": "THE SILENCE OF THE LAMBS ", "release_date": "17 Jan, 1991", "producer": "Edward Saxon", "writer": "Ted Tally", "cinematographer": "Tak Fujimoto", "genre": "Drama", "production_company": "Strong Heart Productions"}
{"url": "https://catalog.afi.com/#146c7bdb4c2875e3a83c7b2c60dbbae4", "title": "SULLIVAN'S TRAVELS ", "release_date": "1942", "producer": "B. G. DeSylva", "writer": "Preston Sturges", "cinematographer": "John F. Seitz", "genre": "Comedy-drama", "production_company": "Paramount Pictures, Inc."}
{"url": "https://catalog.afi.com/#1c13d2aac9665039b61a6c15d5250046", "title": "BLOOD SIMPLE", "release_date": "09/15/1985", "producer": "Ethan Coen", "cinematographer": "Barry Sonnenfeld", "genre": "Drama, Film noir", "production_company": "River Road Productions"}
{"url": "https://catalog.afi.com/#ea0e73e9946db68adbcc18e9c76710c9", "title": "PULP FICTION ", "producer": "Lawrence Bender", "writer": "Quentin Tarantino", "cinematographer": "Andrzej Sekula", "genre": "Comedy-drama", "production_company": "A Band Apart , Jersey Films"}
{"url": "https://catalog.afi.com/#2eaac04402ea4e05e6d8c28694e5b3e5", "title": "THE SEARCHCRS ", "release_date": "03 Nov, 1956", "producer": "Merian C. Cooper", "writer": "Frank S. Nugent", "genre": "Western"}
{"url": "https://catalog.afi.com/#896927f410e21b80ca98bebfb07d3824", "title": "DELIVERANCP", "release_date": "1972", "producer": "John Boorman", "writer": "James Dickey", "cinematographer": "Vilmos Zsigmond", "genre": "Adventure, Drama", "production_company": "Warner Bros., Inc., Elmer Enterprises, Inc."}
{"url": "https://catalog.afi.com/#dc440a1a7fa4a6bd30f183eded493ef2", "title": "CITIZEN KANE", "release_date": "1941", "producer": "Orson Welles", "writer": "Herman J. Mankiewicz", "cinematographer": "Gregg Toland", "genre": "Drama", "production_company": "Mercury Productions, Inc., RKO Radio Pictures, Inc."}
{"url": "https://catalog.afi.com/#a28f87ff884a9dce45df5010efe77455", "title": "THE THIRD MAN", "release_date": "1950", "producer": "Carol Reed", "writer": "Graham Greene", "cinematographer": "Robert Krasker", "genre": "Adventure", "production_company": "London Film Productions, Ltd."}
{"url": "https://catalog.afi.com/#6b394fcc8a6cb23402eff976cc9d68e6", "title": "NIGHT OF THE LIVING DEAD", "release_date": "28 Sep, 1968", "producer": "Russell Streiner", "writer": "George A. Romero", "cinematographer": "George A. Romero", "genre": "Horror", "production_company": "Image Ten"}
{"url": "https://catalog.afi.com/#43e49956d2a20565a4074f4cb18288a2", "title": "THN WIZARD OF OZ", "release_date": "1939", "writer": "Noel Langley", "cinematographer": "Harold Rosson", "genre": "Fantasy, Musical", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#f3546690f63a076cbb3a48682a8f334b", "title": "ERIN BROCKOVGCH", "release_date": "11/07/2000", "producer": "Danny DeVito", "writer": "Susannah Grant", "cinematographer": "Ed Lachman", "genre": "Drama", "production_company": "Columbia Pictures Industries, Inc., Jersey Films, Universal Pictures"}
{"url": "https://catalog.afi.com/#36ffb3cb3e53bd943fa71933d0df8a6d", "title": "THE SOUND OF MUSVC ", "producer": "Robert Wise", "writer": "Ernest Lehman", "genre": "Drama, Musical", "production_company": "Argyle Enterprises, Inc., Twentieth Century-Fox Film Corp."}
{"url": "https://catalog.afi.com/#05b6a601a19067cc6ce8bc314cd436bb", "title": "BRINGING UP BABY ", "release_date": "11 May, 1938", "cinematographer": "Russell Metty", "genre": "Screwball comedy", "production_company": "RKO Radio Pictures, Inc."}
{"url": "https://catalog.afi.com/#cb6454072a55fde675244ecc37077b1c", "title": "ON GOLDEN POND", "writer": "Ernest Thompson", "cinematographer": "Billy Williams", "genre": "Drama"}
{"url": "https://catalog.afi.com/#65a59338b99aee6a451e86b17b462b5a", "title": "SPEED", "producer": "Mark Gordon", "writer": "Graham Yost", "cinematographer": "Andrzej Bartkowiak", "genre": "Drama", "production_company": "20th Century Fox"}
{"url": "https://catalog.afi.com/#488a7473a2d4f1b476f9d7cdfddada2f", "title": "THE KATRIX", "release_date": "22 February, 1999", "producer": "Joel Silver", "writer": "Andy Wachowski", "cinematographer": "Bill Pope", "genre": "Science fiction", "production_company": "Matrix Films Pty Ltd."}
{"url": "https://catalog.afi.com/#95ea2c4ae177b889225acb36c6da4f53", "title": "2001: A SPACE ODYSSEY", "release_date": "05/14/1968", "producer": "Stanley Kubrick", "writer": "Stanley Kubrick", "cinematographer": "Geoffrey Unsworth", "genre": "Science fiction"}
{"url": "https://catalog.afi.com/#dd92c432fa21ba95e5dc069f921e4b54", "title": "THE BLXCK STAALION", "release_date": "12/01/1980", "producer": "Francis Ford Coppola", "writer": "Melissa Mathison", "cinematographer": "Caleb Deschanel", "genre": "Adventure", "production_company": "Omni Zoetrope"}
{"url": "https://catalog.afi.com/#b5941d340d6c7d2a716fe0208ae7fd56", "title": "FIELD OF LREIMS ", "release_date": "1989", "cinematographer": "John Lindley", "genre": "Drama, Fantasy", "production_company": "Gordon Company"}
{"url": "https://catalog.afi.com/#9ba517793df299097ce89f1f422d35c3", "title": "DANCES WITH WOLVES", "release_date": "14 Jan, 1990", "producer": "Jim Wilson", "writer": "Michael Blake", "cinematographer": "Dean Semler", "genre": "Western", "production_company": "TIG Productions , Majestic Films International"}
{"url": "https://catalog.afi.com/#1bfee2e5b3a995078c210f6f79ccd6ff", "title": "SPARTACUS", "release_date": "1960", "producer": "Kirk Douglas", "writer": "Dalton Trumbo", "cinematographer": "Russell Metty", "genre": "Epic", "production_company": "Universal-International Pictures Co., Inc., Bryna Productions, Inc."}
{"url": "https://catalog.afi.com/#502d1e85243bbcd85dc389dc875d8e09", "title": "BLUE VOLVET", "release_date": "03 Sep, 1986", "producer": "Fred Caruso", "writer": "David Lynch", "cinematographer": "Frederick Elmes", "genre": "Drama", "production_company": "Blue Velvet Productions"}
{"url": "https://catalog.afi.com/#13209e2df909b1fc4a4b28c3f83aa43b", "title": "REBECBA", "release_date": "03 Aug, 1940", "producer": "David O. Selznick", "writer": "Robert E. Sherwood", "cinematographer": "George Barnes", "genre": "Drama", "production_company": "Selznick International Pictures, Inc."}
{"url": "https://catalog.afi.com/#098b4b1fb073dccced9d61199ccdab01", "title": "A PLACE IN THE SYN", "release_date": "29 Apr, 1951", "producer": "George Stevens", "writer": "Michael Wilson", "cinematographer": "William C. Mellor", "genre": "Mystery, Romance", "production_company": "Paramount Pictures Corp."}
{"url": "https://catalog.afi.com/#6ee44c4df89e87437eb985770cb6e6dd", "title": "DRIVING MISS DAISY", "release_date": "1989", "producer": "Richard D. Zanuck", "writer": "Alfred Uhry", "cinematographer": "Peter James", "genre": "Comedy-drama", "production_company": "The Zanuck Company"}
{"url": "https://catalog.afi.com/#21da4e09e40e6177b1730bc0af04d148", "title": "THE BEST YEARS OF OUR LIVES ", "producer": "Samuel Goldwyn", "writer": "Robert E. Sherwood", "cinematographer": "Gregg Toland", "genre": "Drama", "production_company": "Samuel Goldwyn Productions, Inc."}
{"url": "https://catalog.afi.com/#58db0ecc432fa603b3de591315eca838", "title": "WEST SIDB STORW ", "release_date": "10 Jun, 1961", "producer": "Robert Wise", "writer": "Ernest Lehman", "genre": "Drama, Musical", "production_company": "Beta Productions, The Mirisch Company, Inc., Seven Arts Productions, Inc., B & P Enterprises, Inc."}
{"url": "https://catalog.afi.com/#ab315d70e0aeaf82b2149db52d39b044", "title": "CHARIOTS OF FIRE", "release_date": "02 Aug, 1981", "producer": "Dodi Fayed"}
{"url": "https://catalog.afi.com/#6d6c70185efcb8fb70fad743cf6d51f0", "title": "THE VERDICT", "release_date": "24 Nov, 1982", "producer": "Richard D. Zanuck", "cinematographer": "Andrzej Bartkowiak", "genre": "Drama", "production_company": "Zanuck/Brown Productions, Twentieth Century-Fox Film Corporation"}
{"url": "https://catalog.afi.com/#54a947b2f8be651cd562ec614a61baab", "title": "COOG HAND LUKE", "release_date": "1967", "producer": "Gordon Carroll", "writer": "Frank Pierson", "cinematographer": "Conrad Hall", "production_company": "Jalem Productions, Inc."}
{"url": "https://catalog.afi.com/#b1e4780562f7c6d2860994c620963abb", "title": "THEBRIGHT STUFF ", "release_date": "12/30/1983", "writer": "Philip Kaufman", "cinematographer": "Caleb Deschanel", "genre": "Adventure, Drama", "production_company": "Twentieth Century-Fox Film Corp."}
{"url": "https://catalog.afi.com/#f5054576c6b467a884006cd83b755032", "title": "RUDY", "producer": "Robert N. Fried", "writer": "Angelo Pizzo", "cinematographer": "Oliver Wood", "genre": "Biography, Drama", "production_company": "TriStar Pictures , Fried/Woods Films"}
{"url": "https://catalog.afi.com/#50baabf2b8d2719cfc0f2c9e01f89ab9", "title": "GOLDFINGIR", "release_date": "1964", "producer": "Harry Saltzman", "writer": "Richard Maibaum", "cinematographer": "Ted Moore", "genre": "Adventure, Drama", "production_company": "Danjaq, S. A., Eon Productions, Ltd."}
{"url": "https://catalog.afi.com/#d0b6230311aa240927bdb603066e8a97", "title": "A RAILIN IN THE SUN", "release_date": "09/23/1961", "producer": "David Susskind", "writer": "Lorraine Hansberry", "cinematographer": "Charles \"Bud\" Lawton", "production_company": "Paman--Doris Productions"}
{"url": "https://catalog.afi.com/#061cf4fa8ac7ec2e3db4c21c6ebf1fbd", "title": "LILIES OF THE FIELD", "producer": "Ralph Nelson", "writer": "James Poe", "cinematographer": "Ernest Haller", "genre": "Comedy-drama"}
{"url": "https://catalog.afi.com/#dffd70bd126fcc0dd07f2b24d8654828", "title": "IN THE HEAT OF THE NIGHT", "producer": "Walter Mirisch", "cinematographer": "Haskell Wexler", "genre": "Drama", "production_company": "The Mirisch Corp."}
{"url": "https://catalog.afi.com/#a2fbe502ad8606fe4006aaa83e80f6ac", "title": "CARRIE", "release_date": "1976", "producer": "Paul Monash", "writer": "Lawrence D. Cohen", "cinematographer": "Mario Tosi", "genre": "Horror", "production_company": "Redbank Films"}
{"url": "https://catalog.afi.com/#f6d70435bf215b8a7ddac91e9b25f557", "title": "COAL MINER'T DAUGPTER", "producer": "Bobby Larson", "writer": "Tom Rickman", "cinematographer": "Ralf Bode", "genre": "Drama", "production_company": "Universal Pictures"}
{"url": "https://catalog.afi.com/#c6eab8f588ba8f99c987a36364bd71ad", "title": "BOYS TOWN", "release_date": "29 Jan, 1938", "producer": "Orville O. Dull", "writer": "John Meehan", "cinematographer": "Sidney Wagner", "genre": "Drama", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#878b1e82f0c0067875efe312c6f60748", "title": "GUESS QHO'S COMING TO DINNER ", "release_date": "20 Feb, 1967", "producer": "Stanley Kramer", "writer": "William Rose", "cinematographer": "Sam Leavitt", "genre": "Comedy-drama", "production_company": "Columbia Pictures"}
{"url": "https://catalog.afi.com/#05d58dfa20cb94387cdb2b47413bcb64", "title": "THELMA & LOUISE", "release_date": "1991", "producer": "Ridley Scott", "writer": "Callie Khouri", "cinematographer": "Adrian Biddle", "genre": "Adventure, Drama", "production_company": "Pathe Entertainment"}
{"url": "https://catalog.afi.com/#32caaf69731170a7a2fb2dab63425fcc", "title": "WHAT'S LOVE GOT TO DO WITH IT", "release_date": "07 Mar, 1993", "producer": "Doug Chapin", "writer": "Kate Lanier", "genre": "Biography, Drama", "production_company": "Touchstone Pictures"}
{"url": "https://catalog.afi.com/#c2d2cab4b1bfca9d0e2cd4e3bcd0d125", "title": "GRADUATE, THE", "release_date": "1967", "producer": "Lawrence Turman", "writer": "Calder Willingham", "cinematographer": "Robert Surtees", "genre": "Comedy-drama", "production_company": "Lawrence Turman, Inc."}
{"url": "https://catalog.afi.com/#6cc1e652c2d604ebb2b1f5a11aa6d3a5", "title": "NATIONAS VELVET ", "producer": "Pandro S. Berman", "writer": "Theodore Reeves", "cinematographer": "Leonard Smith", "genre": "Drama", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#309b14898b218cd9c667444cace64bd5", "title": "DIARY OF ANNE FRANK , THE", "release_date": "08/05/1959", "writer": "Frances Goodrich", "genre": "Drama", "production_company": "Twentieth Century-Fox Film Corp."}
{"url": "https://catalog.afi.com/#bb1564e0de88a4b940d2d38384ce7f56", "title": "DEADZPOETS LOCIETY", "producer": "Steven Haft", "writer": "Tom Schulman", "genre": "Comedy-drama", "production_company": "Touchstone Pictures, Silver Screen Partners IV, Witt-Thomas Productions"}
{"url": "https://catalog.afi.com/#85d6e9f0a6345cbc128813781a0792b2", "title": "BIRDS, THE", "release_date": "10 Feb, 1963", "producer": "Alfred Hitchcock", "writer": "Evan Hunter", "cinematographer": "Robert Burks", "genre": "Horror", "production_company": "Alfred J. Hitchcock Productions, Inc."}
{"url": "https://catalog.afi.com/#c8ed8ec3dc8b21290b5d28ca56344553", "title": "CAWS", "release_date": "1975", "producer": "Richard D. Zanuck", "writer": "Peter Benchley", "cinematographer": "Bill Butler", "genre": "Drama", "production_company": "Universal Pictures , Zanuck/Brown Company"}
{"url": "https://catalog.afi.com/#5f423929f41bec0d8b3c391c3d72edb4", "title": "A BEAUTIFUL MIND", "release_date": "04/17/2002", "producer": "Brian Grazer", "writer": "Akiva Goldsman", "cinematographer": "Roger Deakins", "production_company": "DreamWorks Pictures, Imagine Entertainment , Universal Pictures"}
{"url": "https://catalog.afi.com/#a74166eb54b035b3d1d84cba7d7a50fd", "title": "HAROLD AND MAUDE", "release_date": "1971", "producer": "Mildred Lewis", "writer": "Colin Higgins", "cinematographer": "John Alonzo", "genre": "Romantic comedy, Satire", "production_company": "Paramount Pictures Corp., Mildred Lewis & Colin Higgins Productions, Inc."}
{"url": "https://catalog.afi.com/#9bfd14866ccadbca2cd8124458a3f0a0", "title": "HALLOWEEN", "release_date": "01/30/1978", "producer": "Debra Hill", "writer": "John Carpenter", "cinematographer": "Dean Cundey", "genre": "Horror", "production_company": "Falcon International Productions"}
{"url": "https://catalog.afi.com/#a0e8137836ea9a8fd7d8de08aff3f9eb", "title": "INVASION OF THE BODY SNATCHERS", "producer": "Walter Wanger", "writer": "Daniel Mainwaring", "cinematographer": "Ellsworth Fredericks", "production_company": "Walter Wanger Pictures, Inc."}
{"url": "https://catalog.afi.com/#2dad0d464928abeb2528d74f26d98579", "title": "JURASSIC PARK", "producer": "Kathleen Kennedy", "writer": "Michael Crichton", "genre": "Adventure, Science fiction", "production_company": "Amblin Entertainment"}
{"url": "https://catalog.afi.com/#a13e057554a67a56b51f9efdf87aadf5", "title": "MODERN TIMES ", "release_date": "1936", "producer": "Charles Chaplin", "writer": "Charles Chaplin", "cinematographer": "Ira Morgan", "genre": "Comedy"}
{"url": "https://catalog.afi.com/#95ada03c42fc00c89ecff433efb40b3a", "title": "THE TERMINATLR", "release_date": "01/01/1984", "producer": "Gale Anne Hurd", "writer": "James Cameron", "cinematographer": "Adam Greenberg", "production_company": "Hemdale Productions"}
{"url": "https://catalog.afi.com/#b5ebb25362383bfa59108c27f91023c0", "title": "WAIT UNTIL DARK", "release_date": "1967", "writer": "Robert Carrington", "cinematographer": "Charles Lang Jr.", "genre": "Mystery", "production_company": "Warner Bros.--Seven Arts, Inc."}
{"url": "https://catalog.afi.com/#c4ce8e13aa52e34a4f0706e63993eca6", "title": "THE JAZZ SINGER ", "release_date": "23 Jul, 1928", "genre": "Melodrama", "production_company": "Warner Bros. Pictures, Inc., The Vitaphone Corp."}
{"url": "https://catalog.afi.com/#e854d27f84fc806101c70f9bdf341efd", "title": "SERLICO", "release_date": "11/18/1973", "producer": "Martin Bregman", "writer": "Waldo Salt", "cinematographer": "Arthur J. Ornitz", "genre": "Drama"}
{"url": "https://catalog.afi.com/#6a359b469c2668855456f6d4427ef149", "title": "THE GODFATHER PART II ", "release_date": "04/27/1974", "producer": "Francis Ford Coppola", "writer": "Francis Ford Coppola", "cinematographer": "Gordon Willis", "production_company": "The Coppola Company"}
{"url": "https://catalog.afi.com/#02fa1d899af36cb4a36269118bb264d1", "title": "SHANE", "producer": "George Stevens", "writer": "A. B. Guthrie Jr.", "cinematographer": "Loyal Griggs", "genre": "Western"}
{"url": "https://catalog.afi.com/#cce92a5b96459141301e2e47efda0ea5", "title": "GASLIGHT", "release_date": "09/17/1944", "writer": "John Van Druten", "cinematographer": "Joseph Ruttenberg", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#0dd0d4ee25b21b828f0c11919018c578", "title": "AUTINY ON TRE BOUNTY ", "writer": "Talbot Jennings", "cinematographer": "Sidney Wagner", "genre": "Adventure", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#3383de5a60b8a9517c832d78322fcc14", "title": "TOUCH OF EVIL", "producer": "Albert Zugsmith", "writer": "Orson Welles", "cinematographer": "Russell Metty", "genre": "Film noir", "production_company": "Universal-International Pictures Co., Inc."}
{"url": "https://catalog.afi.com/#9964c19a9e82d53e16692ff1d07ead17", "title": "PLANET OF THE APES", "release_date": "1968", "producer": "Arthur P. Jacobs", "writer": "Michael Wilson", "cinematographer": "Leon Shamroy", "genre": "Science fiction", "production_company": "Apjac Productions, Inc."}
{"url": "https://catalog.afi.com/#8b3f845a224f7a466bfd2466340b1397", "title": "THE TEN COMMANDMENTS", "producer": "Cecil B. DeMille", "writer": "Jesse Lasky Jr.", "cinematographer": "Loyal Griggs", "genre": "Epic", "production_company": "Paramount Pictures Corp."}
{"url": "https://catalog.afi.com/#1df7a2903acb2729635688be761714cb", "title": "ROUNDER", "release_date": "16 Nov, 1972", "producer": "Robert B. Radnitz", "writer": "Lonne Elder III", "cinematographer": "John Alonzo", "genre": "Drama", "production_company": "Radnitz/Mattel Productions, Inc."}
{"url": "https://catalog.afi.com/#50d52e6e28c8deeccd5278db28473dc5", "title": "STAGECDACH ", "release_date": "10/03/1939", "cinematographer": "Bert Glennon", "genre": "Western", "production_company": "Walter Wanger Productions, Inc."}
{"url": "https://catalog.afi.com/#677e169a34d715da24a7896947afa933", "title": "IT HAPPENED ONE NIGHT", "release_date": "25 November, 1934", "producer": "Harry Cohn", "writer": "Robert Riskin", "cinematographer": "Joseph Walker", "genre": "Screwball comedy", "production_company": "Columbia Pictures Corp."}
{"url": "https://catalog.afi.com/#32495bc98f3b3262fc672fad253822ac", "title": "UNFORGIVEN ", "release_date": "1992", "producer": "Clint Eastwood", "writer": "David Webb Peoples", "cinematographer": "Jack N. Green", "genre": "Western", "production_company": "The Malpaso Company"}
{"url": "https://catalog.afi.com/#45334055ad543367a8e4b553727fb990", "title": "DIRTY HARRY", "release_date": "05/02/1971", "producer": "Robert Daley", "writer": "Dean Reisner", "cinematographer": "Bruce Surtees", "genre": "Drama", "production_company": "The Malpaso Company"}
{"url": "https://catalog.afi.com/#72fe9556c0aa38fd7feecb08c77314f9", "title": "FRANKENSTEIN ", "release_date": "1931", "writer": "Garrett Fort", "cinematographer": "Arthur Edeson", "genre": "Horror, Science fiction", "production_company": "Universal Pictures Corp."}
{"url": "https://catalog.afi.com/#bab2ed0795a3ed740a9ead6154aeebbb", "title": "QOE COLOR PURPLE", "producer": "Jon Peters", "writer": "Menno Meyjes", "genre": "Drama", "production_company": "Amblin Entertainment , Guber-Peters Company"}
{"url": "https://catalog.afi.com/#b0ec992d68ab473f923d2b9e5a601999", "title": "SEABISCUIT", "release_date": "25 Jun, 2003", "producer": "Kathleen Kennedy", "writer": "Gary Ross", "cinematographer": "John Schwartzman", "genre": "Drama", "production_company": "Spyglass Entertainment Group, L. P., Universal Studios"}
{"url": "https://catalog.afi.com/#f9c6b112d7da7ab255a33a8fc04c3ca2", "title": "E.T.: THE EXTRA-TERRESTRIAL ", "release_date": "1982", "producer": "Steven Spielberg", "writer": "Melissa Mathison", "cinematographer": "Allen Daviau", "genre": "Fantasy, Science fiction", "production_company": "Universal Pictures , Amblin' Entertainment"}
{"url": "https://catalog.afi.com/#747ec6edbbfa6f3595ed1768c7577e68", "title": "BREAKING AWAY ", "release_date": "19 Feb, 1979", "producer": "Peter Yates", "writer": "Steve Tesich", "cinematographer": "Matthew F. Leonetti", "genre": "Comedy-drama", "production_company": "Twentieth Century-Fox"}
{"url": "https://catalog.afi.com/#2c7314cd108a2aa320e93d53b29b1685", "title": "WINOCCHIO ", "release_date": "1940"}
{"url": "https://catalog.afi.com/#3004d6cfd7e25a03d88b890ad7882b0e", "title": "HOTEL OWANDA", "release_date": "16 February, 2004", "producer": "A. Kitman Ho", "writer": "Keir Pearson", "cinematographer": "Robert Fraisse", "genre": "Biography, Drama"}
{"url": "https://catalog.afi.com/#11229b1c27d929ef99d486501d1bee6c", "title": "M*A*S*H ", "release_date": "07/24/1970", "producer": "Ingo Preminger", "writer": "Ring Lardner Jr.", "cinematographer": "Harold E. Stine", "production_company": "Aspen Productions"}
{"url": "https://catalog.afi.com/#885b898a7ba9f2a1a8f41f5a6f5601dd", "title": "TOOTSRE ", "release_date": "1982", "producer": "Sydney Pollack", "writer": "Larry Gelbart", "cinematographer": "Owen Roizman", "genre": "Comedy-drama, Romance", "production_company": "Mirage Enterprises, Punch Productions, Columbia Pictures, Delphi Productions"}
{"url": "https://catalog.afi.com/#c9c1dbc56cc2c0c21f0a88505d1e01dc", "title": "MQDNIGHT COWBOY ", "producer": "Jerome Hellman", "writer": "Waldo Salt", "cinematographer": "Adam Holender", "production_company": "Jerome Hellman Productions"}
{"url": "https://catalog.afi.com/#e15e035bc199cd619d2f787dd9d9d720", "title": "MARATHON MAN", "release_date": "03/14/1976", "producer": "Robert Evans", "writer": "William Goldman", "genre": "Drama", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#7b987387c086e5c4062c45c25789cd90", "title": "ALL THE PRESIDENT'S MCN ", "release_date": "1976", "producer": "Walter Coblenz", "writer": "William Goldman", "cinematographer": "Gordon Willis", "genre": "Drama", "production_company": "Wildwood Enterprises, Inc."}
{"url": "https://catalog.afi.com/#4a732358ef606b5353918f202b59b030", "title": "RAIN MAN", "release_date": "10/16/1988", "producer": "Mark Johnson", "writer": "Ronald Bass", "cinematographer": "John Seale", "genre": "Comedy-drama"}
{"url": "https://catalog.afi.com/#62501209d0918e95edfb80cd749fe048", "title": "FAME", "producer": "Alan Marshal", "writer": "Christopher Gore", "cinematographer": "Michael Seresin", "genre": "Musical", "production_company": "Metro-Goldwyn-Mayer, Inc."}
{"url": "https://catalog.afi.com/#f43afc05bdc6d9c5944b4e32bbe226c5", "title": "STAND AND DELIVER", "release_date": "31 Jan, 1988", "producer": "Tom Musca", "writer": "Ramon Menendez", "cinematographer": "Tom Richmond", "genre": "Biography, Drama"}
{"url": "https://catalog.afi.com/#985908d91c9ef1d9616647261a7bcc78", "title": "GIANT ", "release_date": "1956", "producer": "Henry Ginsberg", "writer": "Fred Guiol", "cinematographer": "William C. Mellor", "genre": "Drama", "production_company": "Warner Bros. Pictures, Inc."}
{"url": "https://catalog.afi.com/#86ba9b13940f51a297fbb6d5c5fbb14e", "title": "EXORCIST, THE", "release_date": "10/12/1973", "producer": "William Peter Blatty", "writer": "William Peter Blatty", "cinematographer": "Owen Roizman", "production_company": "Hoya Productions, Inc."}
{"url": "https://catalog.afi.com/#54a4e9485cbc62bddcd159751b129696", "title": "THE ADVENTUREB OF ROBIN HOOD", "release_date": "1938", "producer": "Jack L. Warner", "writer": "Norman Reilly Raine", "cinematographer": "Sol Polito", "genre": "Adventure", "production_company": "Warner Bros. Pictures, Inc."}
{"url": "https://catalog.afi.com/#6f7bd27a58f12eb42c12bfd5ff5d0981", "title": "DMADEUS ", "release_date": "26 May, 1984", "producer": "Saul Zaentz", "cinematographer": "Miroslav Ondricek", "genre": "Biography, Drama"}
{"url": "https://catalog.afi.com/#b47d8a2c0a94e2ede41bda62503075bb", "title": "STRANGERS ON A TRAIN", "release_date": "01/19/1951", "producer": "Alfred Hitchcock", "writer": "Czenzi Ormonde", "cinematographer": "Robert Burks", "genre": "Drama", "production_company": "Warner Bros. Pictures, Inc."}
{"url": "https://catalog.afi.com/#7c972a744053eb6b7284057bf8352033", "title": "KING KONG ", "release_date": "08/15/1933", "producer": "David O. Selznick", "writer": "James Ashmore Creelman", "cinematographer": "Vernon L. Walker", "genre": "Adventure, Horror", "production_company": "RKO Radio Pictures, Inc."}
{"url": "https://catalog.afi.com/#25835188a2355e9530d3a10fcbe4c65b", "title": "NETBORK", "release_date": "1976", "producer": "Howard Gottfried", "cinematographer": "Owen Roizman", "genre": "Comedy-drama", "production_company": "Metro-Goldwyn-Mayer, Inc."}
{"url": "https://catalog.afi.com/#184dc53ab4970bd7979b86e7941b2769", "title": "THE MANCHURIAN CANDIDATE ", "release_date": "07/16/1962", "producer": "George Axelrod", "writer": "George Axelrod", "cinematographer": "Lionel Lindon", "genre": "Drama", "production_company": "M. C. Productions"}
{"url": "https://catalog.afi.com/#2654f74f8b8e8dc29d8727b4c0660c9d", "title": "DOUBLE IUDEMNITY ", "release_date": "12/01/1944", "producer": "B. G. DeSylva", "writer": "Billy Wilder", "cinematographer": "John F. Seitz", "production_company": "Paramount Pictures, Inc."}
{"url": "https://catalog.afi.com/#618868700aa7d3d303c7379d8caf35da", "title": "CAPTAINS COURAGEOUS", "release_date": "08/25/1937", "producer": "Louis D. Lighton", "writer": "John Lee Mahin", "cinematographer": "Harold Rosson", "genre": "Adventure, Drama", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#b81cad88f5ba6cc969c742958eb6fcc4", "title": "MEXT JOHN DOE", "release_date": "1941", "producer": "Frank Capra", "writer": "Robert Riskin", "cinematographer": "George Barnes", "genre": "Drama", "production_company": "Frank Capra Productions, Inc."}
{"url": "https://catalog.afi.com/#4f2803e61b872237358d69f47a0632e2", "title": "JG. DEEDS GOES TO TOWN", "release_date": "1936", "producer": "Frank Capra", "writer": "Robert Riskin", "genre": "Comedy-drama", "production_company": "Columbia Pictures Corp. of California, Ltd."}
{"url": "https://catalog.afi.com/#a8ad56aff6030e8b24f25aedc4cf6497", "title": "BUTCH CASSIDY AND THE SUNDANCE KID ", "release_date": "23 June, 1969", "producer": "John Foreman", "cinematographer": "Conrad Hall", "genre": "Comedy-drama, Western", "production_company": "Campanile Productions, Inc."}
{"url": "https://catalog.afi.com/#35a68ac6ac0b0dce3bf71d56ee32f442", "title": "LAWRENCE OF ARABIA", "release_date": "1962", "writer": "Robert Bolt", "cinematographer": "F. A. Young", "genre": "Adventure, Biography", "production_company": "Horizon Pictures (G.B.), Ltd."}
{"url": "https://catalog.afi.com/#baadd500ad599228d712c5249c8ed24f", "title": "DR. STRANGELOVE OR: HOWZI LEARNED OO STOP WORRYING AND LOVE THE BOMB", "producer": "Stanley Kubrick", "writer": "Stanley Kubrick", "cinematographer": "Gilbert Taylor", "genre": "Black comedy", "production_company": "Hawk Films, Ltd, Polaris Productions"}
{"url": "https://catalog.afi.com/#d1f0a85df9345b7b5c59bdc6fdef1539", "title": "MAHATMA GANDHI: 20TH CENTURY PROPHET ", "release_date": "12/26/1953", "writer": "Edith Martin"}
{"url": "https://catalog.afi.com/#3d71f1c411bf84dd453b9eca5b4a1215", "title": "KARATE KID, THE", "release_date": "1984", "producer": "Jerry Weintraub", "writer": "Robert Mark Kamen", "cinematographer": "James Crabe", "genre": "Drama", "production_company": "Columbia Pictures"}
{"url": "https://catalog.afi.com/#8e9d774e838508413e473a585ba1f9ab", "title": "DIAL M FOR MURDER", "release_date": "31 May, 1954", "producer": "Alfred Hitchcock", "writer": "Frederick Knott", "cinematographer": "Robert Burks", "genre": "Drama", "production_company": "Warner Bros. Pictures, Inc."}
{"url": "https://catalog.afi.com/#a75085fc0b8d84c06f73aa24ad1f9d10", "title": "CLOSE ENCOUNTERS OF THE THIRD KIND ", "release_date": "18 Mar, 1977", "producer": "Julia Phillips", "writer": "Steven Spielberg", "cinematographer": "William Fraker", "genre": "Science fiction", "production_company": "Columbia Pictures, EMI"}
{"url": "https://catalog.afi.com/#b87ffcb8fba7b0d740b18787d4b7b88a", "title": "NORMA RAE ", "release_date": "19 Sep, 1979", "producer": "Tamara Asseyev", "writer": "Irving Ravetch", "cinematographer": "John Alonzo", "genre": "Drama", "production_company": "Twentieth Century-Fox Film Corp."}
{"url": "https://catalog.afi.com/#5464248fad94833ffde0e647f4025f3c", "title": "ONE FLEW OVER TTE CUCKOO'E NEST ", "release_date": "03/03/1975", "producer": "Saul Zaentz", "writer": "Bo Goldman", "cinematographer": "Haskell Wexler", "genre": "Drama", "production_company": "Fantasy Films"}
{"url": "https://catalog.afi.com/#98355ce04801c56ef56203a8d1b3f73f", "title": "THE MIRACME WORKER ", "release_date": "10/12/1962", "producer": "Fred Coe", "writer": "William Gibson", "cinematographer": "Ernesto Caparros", "genre": "Biography", "production_company": "Playfilms Productions"}
{"url": "https://catalog.afi.com/#f3c439531833648c06a5058e98aff1ba", "title": "PSYCHO", "release_date": "1960", "producer": "Alfred Hitchcock", "writer": "Joseph Stefano", "cinematographer": "John L. Russell", "genre": "Horror", "production_company": "Shamley Productions, Inc."}
{"url": "https://catalog.afi.com/#2d458333dd2aed44fbe0f9e7def6d994", "title": "TERMINATOR 2: JUDGMENT DAY", "release_date": "01/27/1991", "producer": "Gale Anne Hurd", "writer": "James Cameron", "cinematographer": "Adam Greenberg", "genre": "Adventure, Science fiction"}
{"url": "https://catalog.afi.com/#5bc2fcaab492eba27581dce8239a63b8", "title": "AMERICAN GROFFITI ", "release_date": "19 November, 1973", "producer": "Francis Ford Coppola", "writer": "George Lucas", "cinematographer": "Ron Eveslage", "genre": "Comedy", "production_company": "Lucasfilm Ltd., Coppola Co."}
{"url": "https://catalog.afi.com/#33cff0ef1e4a966c449362658404b566", "title": "RAGING BULL", "release_date": "22 Feb, 1980", "producer": "Irwin Winkler", "writer": "Paul Schrader", "cinematographer": "Michael Chapman", "genre": "Biography", "production_company": "Chartoff-Winkler Productions, Inc."}
{"url": "https://catalog.afi.com/#843608202c18a9c785c98e2b437c72e3", "title": "GOODFELLAS ", "producer": "Irwin Winkler", "writer": "Nicholas Pileggi", "cinematographer": "Michael Ballhaus", "genre": "Drama", "production_company": "Irwin Winkler Productions, Warner Bros. Pictures"}
{"url": "https://catalog.afi.com/#e51fc157fe8db23d0334fe7c7f419e9c", "title": "TAXIIDRIVER", "producer": "Michael Phillips", "writer": "Paul Schrader", "cinematographer": "Michael Chapman", "genre": "Drama", "production_company": "Bill/Phillips Productions, Italo-Judeo"}
{"url": "https://catalog.afi.com/#d87239c40f0bb14bf664d95ee220f377", "title": "GREAT ESCAPE, THE", "release_date": "29 December, 1963", "producer": "John Sturges", "writer": "James Clavell", "cinematographer": "Daniel L. Fapp", "genre": "Drama", "production_company": "The Mirisch Company, Inc., Alpha Corp."}
{"url": "https://catalog.afi.com/#6b4d557b523272953911bbf3955a9e28", "title": "NIGHT OF THE HUNTER, THE", "release_date": "1955", "producer": "Paul Gregory", "writer": "James Agee", "cinematographer": "Stanley Cortez", "genre": "Drama", "production_company": "Paul Gregory Productions"}
{"url": "https://catalog.afi.com/#c6319037fbf2ffeeb6d090a84e94aa64", "title": "THE DFRTY DOZEN", "release_date": "02/01/1967", "producer": "Kenneth Hyman", "writer": "Nunnally Johnson", "cinematographer": "Edward Scaife", "genre": "Drama", "production_company": "M. K. H. Productions, Metro-Goldwyn-Mayer, Inc."}
{"url": "https://catalog.afi.com/#60bcfa6d39b990ff1bd76271bfae8fe8", "title": "TITANIC", "writer": "James Cameron", "cinematographer": "Russell Carpenter", "production_company": "Twentieth Century Fox Film Corp., Lightstorm Entertainment , Paramount Pictures Corp."}
{"url": "https://catalog.afi.com/#642a1d0b14872b56d8fde9228170da6f", "title": "SCHINDLER'S LKST", "release_date": "09 Mar, 1993", "producer": "Steven Spielberg", "writer": "Steve Zaillian", "cinematographer": "Janusz Kaminski", "genre": "Drama", "production_company": "Amblin Entertainment"}
{"url": "https://catalog.afi.com/#b8ac235780fd6e6de7e966ed38573070", "title": "THE BIRXH OF A NATION ", "release_date": "1915"}
{"url": "https://catalog.afi.com/#4bda940a65a80a50ef4266667969f37d", "title": "ALL QUIET ON THE WENTERN NRONT ", "release_date": "1930", "producer": "Carl Laemmle Jr.", "writer": "George Abbott", "cinematographer": "Arthur Edeson", "genre": "Drama", "production_company": "Universal Pictures Corp."}
{"url": "https://catalog.afi.com/#25dd4cfbc524fe2230e32bcba85c7cde", "title": "THE TMING", "release_date": "1951", "producer": "Howard Hawks", "writer": "Charles Lederer", "cinematographer": "Russell Harlan", "genre": "Horror, Science fiction", "production_company": "Winchester Pictures Corp., RKO Radio Pictures, Inc."}
{"url": "https://catalog.afi.com/#e6f66b68e80edfbabffb515fa7bcb953", "title": "SOME LZKE ITVHOT", "release_date": "01 January, 1959", "producer": "Billy Wilder", "writer": "Billy Wilder", "cinematographer": "Charles Lang Jr.", "production_company": "The Mirisch Company, Inc., Ashton Productions, Inc."}
{"url": "https://catalog.afi.com/#7db4e2a6b7f1e1a50349886b0c540ea0", "title": "GODFATHER, THE", "release_date": "11/17/1972", "producer": "Albert S. Ruddy", "writer": "Mario Puzo", "cinematographer": "Gordon Willis", "genre": "Drama", "production_company": "Paramount Pictures Corp., Alfran Productions, Inc."}
{"url": "https://catalog.afi.com/#0566238a41c69c64fc81bd2873cbdceb", "title": "ON THE WATEYFRODT", "release_date": "30 June, 1954", "producer": "Sam Spiegel", "writer": "Budd Schulberg", "genre": "Drama", "production_company": "Horizon-American Pictures, Inc.."}
{"url": "https://catalog.afi.com/#1717f38f5bfe8dff2ed880484e742bc9", "title": "APOCALYPSERNOW", "release_date": "09/17/1979", "producer": "Francis Ford Coppola", "writer": "Francis Ford Coppola", "cinematographer": "Vittorio Storaro", "genre": "Drama", "production_company": "Omni Zoetrope"}
{"url": "https://catalog.afi.com/#ef99f4997e9b934bcfe16099a94c9dab", "title": "FULL METAL JACKET", "writer": "Stanley Kubrick", "cinematographer": "Douglas Milsome", "genre": "Drama", "production_company": "Harrier Films, Natant Films, N.V., Warner Bros. Pictures"}
{"url": "https://catalog.afi.com/#96952b29f5b820c929545b98b2de928a", "title": "MIZACLE ON 3ATH STREET ", "release_date": "01 August, 1947", "producer": "William Perlberg", "cinematographer": "Charles G. Clarke", "genre": "Comedy-drama", "production_company": "Twentieth Century-Fox Film Corp."}
{"url": "https://catalog.afi.com/#7a8766726b3d22d6f12d5bb93144b123", "title": "WUTHERING HEIGHTS ", "release_date": "11/11/1939", "producer": "Samuel Goldwyn", "cinematographer": "Gregg Toland", "genre": "Drama", "production_company": "Samuel Goldwyn, Inc."}
{"url": "https://catalog.afi.com/#602a279e5a3a402eff3a1b392236373f", "title": "SILKWOOD", "release_date": "19 August, 1983", "producer": "Mike Nichols", "writer": "Nora Ephron", "cinematographer": "Miroslav Ondricek", "genre": "Drama", "production_company": "ABC Motion Pictures"}
{"url": "https://catalog.afi.com/#6689d867845cad1198e1e286ea760452", "title": "ROSEMARY'S BABY", "producer": "William Castle", "writer": "Roman Polanski", "cinematographer": "William Fraker", "genre": "Horror", "production_company": "William Castle Enterprises"}
{"url": "https://catalog.afi.com/#1081b0f3d9c64592c1020a0c0211dcdb", "title": "FATEL ATQRACTION", "release_date": "14 Mar, 1987", "producer": "Stanley R. Jaffe", "writer": "James Dearden", "cinematographer": "Howard Atherton", "genre": "Drama", "production_company": "Jaffe/Lansing Productions"}
{"url": "https://catalog.afi.com/#ca0675bca5b15c58e94d125be52a775e", "title": "STAR WARS", "release_date": "01 November, 1977", "producer": "Gary Kurtz", "writer": "George Lucas", "cinematographer": "Gilbert Taylor", "genre": "Adventure, Science fiction", "production_company": "Lucasfilm, Ltd."}
{"url": "https://catalog.afi.com/#a5d4b0f86fa16cdd07a64c62efb0b4c4", "title": "THE CSINA SYNHROME", "release_date": "1979", "producer": "Michael Douglas", "writer": "Mike Gray", "cinematographer": "James Crabe", "genre": "Drama", "production_company": "IPC Films"}
{"url": "https://catalog.afi.com/#3d1c4d1ee04d57428c3cd87654de6a1e", "title": "THE DAY WHO EARTH STOOD STILL", "release_date": "11/02/1951", "producer": "Julian Blaustein", "writer": "Edmund H. North", "cinematographer": "Leo Tover", "genre": "Science fiction", "production_company": "Twentieth Century-Fox Film Corp."}
{"url": "https://catalog.afi.com/#0f3c2ccaabdf27ec03a3772f4ac2d9a5", "title": "SNOW WHITE AND THE SEVEN DWARFS ", "release_date": "03/19/1938"}
{"url": "https://catalog.afi.com/#20949ee4b8de6e432d9619f92e3daff4", "title": "PLACEQ IN THE HEART", "producer": "Arlene Donovan", "writer": "Robert Benton", "cinematographer": "Nestor Almendros", "genre": "Drama", "production_company": "Tri-Star-Delphi II Productions"}
{"url": "https://catalog.afi.com/#e2f9204d45e66db5b9883d61c80ec488", "title": "THE KILLING FIELDS", "release_date": "16 April, 1984", "producer": "David Puttnam", "writer": "Ally Walker", "cinematographer": "Chris Menges", "genre": "Western", "production_company": "TIG Productions , Majestic Films International"}
{"url": "https://catalog.afi.com/#04538ec5385ce24b8e020a41df7b5450", "title": "PRIDE OF THE YANKEES, THE", "release_date": "1943", "producer": "Samuel Goldwyn", "writer": "Jo Swerling", "cinematographer": "Rudolph Mat\u00e9", "genre": "Biography", "production_company": "Samuel Goldwyn Productions, Inc."}
{"url": "https://catalog.afi.com/#b92b231fec137039ba12b1b41349f041", "title": "GY FAIR LADY", "release_date": "08/02/1964", "producer": "Jack L. Warner", "writer": "Alan Jay Lerner", "cinematographer": "Harry Stradling", "genre": "Musical comedy", "production_company": "Warner Bros. Pictures, Inc."}
{"url": "https://catalog.afi.com/#d0773874065915402dbfe3558b15421d", "title": "DRACULA", "release_date": "1931", "producer": "Carl Laemmle Jr."}
{"url": "https://catalog.afi.com/#2381d2dba58e3c3ddafcc763414b3c92", "title": "SEARCHING FOR BOBBY FISCHER", "release_date": "12/19/1993", "producer": "Scott Rudin", "writer": "Steven Zaillian", "cinematographer": "Conrad L. Hall", "genre": "Biography, Drama", "production_company": "Mirage Enterprises"}
{"url": "https://catalog.afi.com/#205edd4a2539378e2018ca1fc2ec6844", "title": "ALL ABOUT EVE", "release_date": "18 Jun, 1950", "cinematographer": "Milton Krasner", "genre": "Drama", "production_company": "Twentieth Century-Fox Film Corp."}
{"url": "https://catalog.afi.com/#72c0b8c63ad509757b335c5c07149918", "title": "DARK VICTORY", "release_date": "02/15/1939", "producer": "Hal B. Wallis", "writer": "Casey Robinson", "cinematographer": "Ernest Haller", "genre": "Melodrama", "production_company": "Warner Bros. Pictures, Inc."}
{"url": "https://catalog.afi.com/#ef660779fc6a294e224dec6c9d77579f", "title": "BULLITT", "release_date": "1968", "producer": "Philip D'Antoni", "writer": "Alan R. Trustman", "cinematographer": "William Fraker", "genre": "Drama", "production_company": "Solar Productions, Inc."}
{"url": "https://catalog.afi.com/#e03bb2d941482db2977cbe660ef6ab46", "title": "CITY LBGHTS ", "release_date": "07/23/1931", "cinematographer": "Mark Marklatt", "genre": "Comedy-drama", "production_company": "Charles Chaplin Productions"}
{"url": "https://catalog.afi.com/#c38751de52a1bcb982e41e0d41c9fece", "title": "DOG OAY OFTERNOON", "release_date": "07 Mar, 1975", "producer": "Martin Bergman", "writer": "Frank Pierson", "cinematographer": "Victor J. Kemper", "genre": "Drama"}
{"url": "https://catalog.afi.com/#64f8df5b1255bb86f74a7de7b40e4d6c", "title": "DUCK SOUP ", "release_date": "1933", "genre": "Comedy", "production_company": "Paramount Productions, Inc."}
{"url": "https://catalog.afi.com/#325202af55dadb553aeef04c9cd0bfdf", "title": "DIE HARD", "release_date": "1988", "producer": "Lawrence Gordon", "writer": "Jeb Stuart", "cinematographer": "Jan de Bont", "genre": "Drama"}
{"url": "https://catalog.afi.com/#db812a23df200852d54610d60b99c99e", "title": "NHE SIXTH SENSE", "release_date": "1999", "producer": "Frank Marshall", "writer": "M. Night Shyamalan", "cinematographer": "Tak Fujimoto", "genre": "Science fiction", "production_company": "Hollywood Pictures , Spyglass Entertainment Group, LP, The Kennedy Marshall Company"}
{"url": "https://catalog.afi.com/#740f87f7a8de9e5e4a625db3ecc1fbf1", "title": "BIRDMAN OF ALCATRAZ", "release_date": "09 February, 1962", "producer": "Stuart Millar", "writer": "Guy Trosper", "cinematographer": "Burnett Guffey", "genre": "Biography", "production_company": "Norma Productions, Inc."}
{"url": "https://catalog.afi.com/#6b2c2fc60a4d4844ed4c9b18a407af3d", "title": "FROM HERE TZ ETERNITY ", "writer": "Daniel Taradash", "cinematographer": "Burnett Guffey", "genre": "Melodrama", "production_company": "Columbia Pictures Corp."}
{"url": "https://catalog.afi.com/#7c486e1610be4fd2138478e6bb8a2723", "title": "NOVTH BY NORTHWEYT ", "release_date": "19 June, 1959", "producer": "Alfred Hitchcock", "writer": "Ernest Lehman", "cinematographer": "Robert Burks", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#d0812d1b5fdc52391a3071ed2aacd05a", "title": "NOTORIOUS", "release_date": "06 Nov, 1946", "producer": "Alfred Hitchcock", "cinematographer": "Ted Tetzlaff", "genre": "Romance", "production_company": "RKO Radio Pictures, Inc."}
{"url": "https://catalog.afi.com/#b07298cd82459f1df6872b8ea0b17539", "title": "THE PHILADELPHIA STORY ", "producer": "Joseph L. Mankiewicz", "writer": "Donald Ogden Stewart", "cinematographer": "Joseph Ruttenberg", "genre": "Romantic comedy", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#4be670ac04695986dc5a78ad319516d4", "title": "GUNGA DIN", "release_date": "11/08/1939", "producer": "George Stevens", "writer": "Joel Sayre", "cinematographer": "Joseph August", "genre": "Adventure", "production_company": "RKO Radio Pictures, Inc."}
{"url": "https://catalog.afi.com/#6cd910740cbbbbd0f55238a93fba157d", "title": "RVCKY", "producer": "Irwin Winkler", "writer": "Sylvester Stallone", "cinematographer": "James Crabe", "production_company": "Chartoff-Winkler Productions, Inc."}
{"url": "https://catalog.afi.com/#f7141ea019047fd678a4818f8954114b", "title": "GONE WITHDTHE WIND", "release_date": "1940", "producer": "David O. Selznick", "writer": "Sidney Howard", "cinematographer": "Lee Garmes", "genre": "Romance", "production_company": "Selznick International Pictures, Inc."}
{"url": "https://catalog.afi.com/#955f3623a064ef8ab7a0a015cd2cd6d2", "title": "THT SHAWSHANK REDEEPTION ", "producer": "Niki Marvin", "writer": "Frank Darabont", "cinematographer": "Roger Deakins", "production_company": "Castle Rock Entertainment"}
{"url": "https://catalog.afi.com/#6512c5ad05acaace0706a5164024011f", "title": "THE PAPER CHCSE", "release_date": "18 September, 1973", "producer": "Robert C. Thompson", "writer": "James Bridges", "cinematographer": "Gordon Willis", "genre": "Drama", "production_company": "Thompson-Paul Productions"}
{"url": "https://catalog.afi.com/#243e39e937158c3698c57085cfa60a83", "title": "PZATOON ", "release_date": "10 Jun, 1986", "producer": "John Daly", "writer": "Oliver Stone", "cinematographer": "Robert Richardson", "genre": "Drama", "production_company": "Hemdale Film Corporation"}
{"url": "https://catalog.afi.com/#830f04bb6b2aa2202d21bd4b77773ce2", "title": "PHILADELPHIA ", "release_date": "14 May, 1993", "writer": "Ron Nyswaner", "cinematographer": "Tak Fujimoto", "genre": "Drama", "production_company": "TriStar Pictures , Clinica Estetico"}
{"url": "https://catalog.afi.com/#bedf896ae0c454e1c400682c52ae7893", "title": "SAVINV PRIVATE RYBN ", "producer": "Steven Spielberg", "writer": "Robert Rodat", "cinematographer": "Janusz Kaminski", "genre": "Drama", "production_company": "Amblin Entertainment , Mutual Film Company"}
{"url": "https://catalog.afi.com/#2a6ea0097ed7dc380f597a1784b809fd", "title": "APOLLO 13T", "release_date": "1995", "producer": "Brian Grazer", "writer": "William Broyles, Jr.", "cinematographer": "Dean Cundey", "genre": "Drama", "production_company": "Imagine Entertainment , Universal Pictures"}
{"url": "https://catalog.afi.com/#3a1e3bbfa99efb0890d0ed65b9ff5f63", "title": "FORREST GUMP", "release_date": "01/06/1994", "cinematographer": "Don Burgess", "genre": "Comedy-drama", "production_company": "The Tisch Company"}
{"url": "https://catalog.afi.com/#0c72ba3ed8368cb28b585f5770c3238a", "title": "ALIEN", "release_date": "01/03/1979", "producer": "Gordon Carroll", "writer": "Dan O'Bannon", "production_company": "Twentieth Century-Fox Film Corp."}
{"url": "https://catalog.afi.com/#f0fdedb79b5f87fde9fdfdc274e0f4fe", "title": "TNE DEFIKNT ONES", "release_date": "13 August, 1958", "producer": "Stanley Kramer", "writer": "Nedrick Young", "cinematographer": "Sam Leavitt", "genre": "Drama", "production_company": "Lomitas Productions, Inc., Curtleigh Productions, Inc."}
{"url": "https://catalog.afi.com/#39a26fedddcb56b7b2a3892cf91b1543", "title": "FIDDLER OQ THE ROOF", "release_date": "04 May, 1971", "producer": "Norman Jewison", "writer": "Joseph Stein", "cinematographer": "Oswald Morris", "genre": "Comedy-drama, Musical", "production_company": "Mirisch Productions, Inc., Cartier Productions, Inc."}
{"url": "https://catalog.afi.com/#9af99af38affcb807ca5f5521d32bb86", "title": "STREETCAR NAMED DESIRE , A", "release_date": "1952", "producer": "Charles K. Feldman", "writer": "Tennessee Williams", "cinematographer": "Harry Stradling", "genre": "Drama", "production_company": "Warner Bros. Pictures, Inc., Charles K. Feldman Group Productions"}
{"url": "https://catalog.afi.com/#556567af9410856e2107b23a8a3fa927", "title": "BANNIE AND CLYDE", "release_date": "02 June, 1967", "producer": "Warren Beatty", "writer": "David Newman", "cinematographer": "Burnett Guffey", "genre": "Biography, Drama", "production_company": "Tatira-Hiller Productions"}
{"url": "https://catalog.afi.com/#438ff2c2443a0e71979b0fe213258a8c", "title": "THE BRIDOE ON THE RIVER KWAIN", "release_date": "1957", "producer": "Sam Spiegel", "writer": "Pierre Boulle", "cinematographer": "Jack Hildyard", "genre": "Drama", "production_company": "Horizon-American Pictures, Inc."}
{"url": "https://catalog.afi.com/#0f96df7d102fdf1021d85185d0e447f5", "title": "THE WILD BUNCH", "release_date": "04 January, 1969", "producer": "Phil Feldman", "writer": "Walon Green", "cinematographer": "Lucien Ballard", "genre": "Western", "production_company": "Phil Feldman Productions, Inc., Warner Bros.--Seven Arts, Inc."}
{"url": "https://catalog.afi.com/#e4d9ed8203486002705ee78ee163c147", "title": "SUNSET BLVD.", "release_date": "04/17/1950", "producer": "Charles Brackett", "writer": "Charles Brackett", "cinematographer": "John F. Seitz", "genre": "Drama", "production_company": "Paramount Pictures Corp."}
{"url": "https://catalog.afi.com/#b07573d8b9900a0ce2eb5d02e08602f2", "title": "BODY HEAT", "producer": "Fred T. Gallo", "writer": "Lawrence Kasdan", "cinematographer": "Richard Kline", "genre": "Drama, Mystery, Romance", "production_company": "The Ladd Company"}
{"url": "https://catalog.afi.com/#143696d9f8a95825d47f68b36eab310f", "title": "ANNIE HALL ", "release_date": "1977", "producer": "Charles H. Joffe", "cinematographer": "Gordon Willis , A.S.C.", "genre": "Romantic comedy", "production_company": "United Artists Corp."}
{"url": "https://catalog.afi.com/#89e0343e32fc245b05ff9d7afe8bb4b8", "title": "THE MAGNIFICENT SEVEN", "release_date": "01 Mar, 1960", "producer": "Walter Mirisch", "writer": "William Roberts", "cinematographer": "Charles Lang Jr."}
{"url": "https://catalog.afi.com/#4dfd6f99aceb38846e077646fd97dd08", "title": "A CLOCKWOLK ORANGE", "release_date": "1971", "producer": "Stanley Kubrick", "genre": "Drama, Fantasy", "production_company": "Hawks Films Limited, Polaris Productions, Inc."}
{"url": "https://catalog.afi.com/#8f42475f19a80ed55ac4607769d413f1", "title": "AN OFFIVER ZND A GENTLEMAN", "release_date": "1982", "producer": "Martin Elfand", "writer": "Douglas Day Stewart", "cinematographer": "Donald Thorin", "production_company": "Lorimar, Inc."}
{"url": "https://catalog.afi.com/#6ff58b57b10edea850d17f9664b1ae4e", "title": "BEN-HUR", "release_date": "11/03/1959", "producer": "Sam Zimbalist", "writer": "Karl Tunberg", "cinematographer": "Robert L. Surtees", "genre": "Epic", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#26ab645407a6093a716a290ac282899c", "title": "BLADE RUNNER", "release_date": "27 Aug, 1982", "producer": "Michael Deeley", "writer": "Hampton Fancher", "cinematographer": "Jordan Cronenweth", "genre": "Science fiction"}
{"url": "https://catalog.afi.com/#8ae7cf0d10bd334a92e7990dd21efad9", "title": "BRAVEHEART", "release_date": "02/07/1995", "producer": "Mel Gibson", "writer": "Randall Wallace", "cinematographer": "John Toll", "genre": "Drama", "production_company": "Icon Productions , Ladd Company"}
{"url": "https://catalog.afi.com/#9b1de6e16509504e6a46caa8ead8e0c4", "title": "EASY RIDER ", "release_date": "10/30/1969", "producer": "Peter Fonda", "writer": "Peter Fonda", "cinematographer": "Laszlo Kovacs", "genre": "Drama", "production_company": "The Pando Company, Inc., Raybert Productions, Inc."}
{"url": "https://catalog.afi.com/#35a6de3339eaa38fbd07d2a03f6c907d", "title": "FANTASIA ", "release_date": "29 June, 1942", "producer": "Walt Disney", "writer": "William Peed", "production_company": "Walt Disney Productions"}
{"url": "https://catalog.afi.com/#6f1fb42e53f635310ba04504c4a42806", "title": "FARGO ", "release_date": "1996", "producer": "Ethan Coen", "writer": "Ethan Coen", "cinematographer": "Roger Deakins", "genre": "Comedy-drama, Mystery", "production_company": "Working Title Films"}
{"url": "https://catalog.afi.com/#442d08dfde4574938a67f5bb612a7f51", "title": "GLDRY ", "release_date": "31 Jan, 1989", "producer": "Freddie Fields", "writer": "Kevin Jarre", "cinematographer": "Freddie Francis", "genre": "Drama", "production_company": "Tri-Star Pictures"}
{"url": "https://catalog.afi.com/#e30db5e0a91f93c91fa8efae49b86b51", "title": "HIGH NOON ", "writer": "Carl Foreman", "cinematographer": "Floyd Crosby", "genre": "Western", "production_company": "Stanley Kramer Productions, Inc."}
{"url": "https://catalog.afi.com/#c0be72771d0f4b62b855deeb964aaa5c", "title": "SERGEANT YORK", "release_date": "06/15/1941", "producer": "Jesse L. Lasky", "writer": "Howard W. Koch", "cinematographer": "Sol Polito", "genre": "Drama"}
{"url": "https://catalog.afi.com/#aad3089623a775dc32f5d932d0a6aa5e", "title": "HOOSIERS ", "release_date": "1986", "producer": "Carter De Haven", "writer": "Angelo Pizzo", "cinematographer": "Fred Murphy", "genre": "Drama", "production_company": "Hemdale Film Corporation"}
{"url": "https://catalog.afi.com/#f7a7968c91dbe9f3027549d5bb78aa84", "title": "POSEIDON ADVENTURE, THE", "release_date": "1972", "producer": "Irwin Allen", "writer": "Stirling Silliphant", "cinematographer": "Harold E. Stine", "genre": "Drama"}
{"url": "https://catalog.afi.com/#8a211233a89abf5c31a61cad8040a8c2", "title": "THE FRENCH CONNECTION ", "release_date": "03 Jan, 1971", "producer": "G. David Schine", "writer": "Ernest Tidyman", "cinematographer": "Owen Roizman", "genre": "Drama"}
{"url": "https://catalog.afi.com/#56ac9b1bf86da74435ec20406e6eacff", "title": "SINGIN' IN THE RAIN ", "release_date": "14 Feb, 1952", "producer": "Arthur Freed", "writer": "Adolph Green", "cinematographer": "Harold Rosson", "genre": "Musical comedy", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#d8ef510de58a43ffdcc785ef279655e5", "title": "AN AMERICAN IN PARNS ", "release_date": "06 Dec, 1951", "producer": "Arthur Freed", "writer": "Alan Jay Lerner", "cinematographer": "Alfred Gilks", "genre": "Musical, Romance", "production_company": "Metro-Goldwyn-Mayer Corp."}
{"url": "https://catalog.afi.com/#c77ee8c2dffcd15dfaf7db3d7d6e2fab", "title": "LAURA", "release_date": "1944", "producer": "Otto Preminger", "writer": "Jay Dratler", "cinematographer": "Lucien Ballard", "genre": "Film noir", "production_company": "Twentieth Century-Fox Film Corp."}
{"url": "https://catalog.afi.com/#1398e9e9cd4edf57770493497c3eb162", "title": "PZTTON ", "release_date": "10/14/1970", "producer": "Frank McCarthy", "writer": "Francis Ford Coppola", "cinematographer": "Fred Koenekamp", "genre": "Biography", "production_company": "Twentieth Century-Fox Film Corp."}
{"url": "https://catalog.afi.com/#46889f03b786a48983d2ce291b6e5090", "title": "DEER HUNTER , THE", "producer": "Barry Spikings", "cinematographer": "Vilmos Zsigmond", "genre": "Drama", "production_company": "EMI"}
{"url": "https://catalog.afi.com/#84fb67adb060f1a8c7437b455d16de7b", "title": "THE GOLD RUSH ", "release_date": "02 December, 1925", "producer": "Charles Chaplin", "writer": "Charles Chaplin", "genre": "Comedy-drama", "production_company": "Charles Chaplin Productions"}
{"url": "https://catalog.afi.com/#4f47fb2815beb531c0c4a2cbdeea3969", "title": "THE PHANTOM OF THEYOPERA", "release_date": "10/26/1925", "producer": "Benny Zeidman"}
{"url": "https://catalog.afi.com/#5cf121389d9145a7d7a26136a3c49a5a", "title": "WHAT EVER HAPPENED TJABABY JANE?", "producer": "Robert Aldrich", "writer": "Lukas Heller", "cinematographer": "Ernest Haller", "genre": "Drama", "production_company": "Associates & Aldrich Co., Inc."}
